# Generated by Django 4.1.3 on 2022-11-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Owners',
            new_name='Owner',
        ),
    ]
