# Generated by Django 4.1.3 on 2022-11-19 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_rename_owners_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF (*).'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Full Name (*).'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='telefone',
            field=models.CharField(max_length=255, verbose_name='Phone Number (*).'),
        ),
    ]
