# Generated by Django 4.1.3 on 2022-11-19 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL([
            "INSERT INTO cars_colorcar (description) VALUES ('yellow');",
            "INSERT INTO cars_colorcar (description) VALUES ('blue');",
            "INSERT INTO cars_colorcar (description) VALUES ('gray');",
            "INSERT INTO cars_modelscar (description) VALUES ('hatch');",
            "INSERT INTO cars_modelscar (description) VALUES ('sedan');",
            "INSERT INTO cars_modelscar (description) VALUES ('convertible');",
        ])
    ]
