# Generated by Django 4.1.3 on 2022-11-19 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20221119_1848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('color', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.colorcar')),
                ('model_car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cars.modelscar')),
            ],
        ),
    ]
